/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import javafx.application.Application
import javafx.scene.Scene
import javafx.scene.layout.Pane
import javafx.stage.Stage

class App : Application() {
    override fun start(stage: Stage) {
        val gameScene = GameScene(800.0, 600.0)
        val ball = BouncingBall(
            radius = 20.0,
            initialX = 400.0,
            initialY = 300.0,
            movement = LinearMovement(3.0, 3.0)
        )
        
        val collisionHandler = BoundaryCollisionHandler()
        val gameLoop = GameLoop(ball, collisionHandler, gameScene)
        
        stage.apply {
            title = "Pelota Rebotando"
            scene = gameScene.scene
            show()
        }
        
        gameLoop.start()
    }
}

fun main() {
    Application.launch(App::class.java)
}
